### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <  

### ISSUE THREAD

**Issue by BenRoz** [flexdinesh/react-redux-boilerplate#1]
Hey, 
After yarn, running yarn start which compile successfully but gives an error in console:
Uncaught SyntaxError: Unexpected token <   (in main.js) 
I am using Windows. 
Any idea why ?

**Comment by flexdinesh** [comment]
@BenRoz I use MacBook and this doesn't happen in macOS. But this needs to be fixed in Windows somehow.

Are you able to debug it? Pl see of you can get the logs so we'll be able to debug it further.

**Comment by marwan38** [comment]
I have the same thing. The main.js being bundled by webpack is the same HTML code - that and sometimes it doesn't show up in the sources.

**Comment by flexdinesh** [comment]
@marwan38 `path` lib should automatically take care of appending the '/' to 'build'. Also I tried this in my machine. When you replace `path: path.resolve(process.cwd(), 'build')` with `path: path.resolve(process.cwd(), '/build')`, npm script `start:production` is failing.

**Comment by flexdinesh** [comment]
I just ran everything in a new windows machine and there were no issues. Is someone still seeing this issue or are we good to close this out?
