### ISSUE TITLE
Unable to start the boilerplate

### ISSUE THREAD

**Issue by ollie314** [flexdinesh/react-redux-boilerplate#11]
Hi,
I encountered the following error when I'm trying to start the boilerplate right after cloning the repo:
`Uncaught TypeError: Cannot read property 'get' of undefined`
Here is the full error on the console.
![react-redux-boilerplate-start-error](https://user-images.githubusercontent.com/321944/41642750-7c90ee78-7469-11e8-94ad-1c17640146a0.png)

## Ecosystem:
OS: win 10
browser: chrome: Version 66.0.3359.139
extensions: adguard, ghostery, redux, react, onetab, boomerang, restlet client
node: 8.11.1
npm: 5.6.0

## Setp to reproduce:
- `git clone https://github.com/flexdinesh/react-redux-boilerplate.git`
- `cd react-redux-boilerplate`
- `npm install`
- `npm start`
- open the browser on  `http://localhost:3000`

## disclaimer
I'm not a guru with react nor with redux

Regards

**Comment by ross-freeagent** [comment]
I think this is related to #12 since we're injecting the `homeReducer`

**Comment by flexdinesh** [comment]
@ollie314 This is fixed now. Apparently I merged a PR without running it in local and it upgraded Redux from v3 to latest v4 and the code isn't syntactically updated to work with v4 and hence the chaos. I have downgraded Redux to v3 with this commit 5ec626d9ae6b9541fe94afa393e20942062a28ef and everything should be fine now.
