### ISSUE TITLE
Fresh Install Error

### ISSUE THREAD

**Issue by ejabu** [flexdinesh/react-redux-boilerplate#13]
I just installed the app by using yarn.

My terminal showed this .. 

`warning " > react-router-redux@5.0.0-alpha.6" has incorrect peer dependency "react@^15".
[5/5] Building fresh packages...
[-/6] ⠄ waiting...
[-/6] ⠄ waiting...
[6/6] ⠄ node-sass
[4/6] ⠄ pngquant-bin
error /home/haliib/aysaar/app1/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/haliib/aysaar/app1/node_modules/pngquant-bin
Output:
⚠ The `/home/haliib/aysaar/app1/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/haliib/aysaar/app1/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
`

**Comment by ejabu** [comment]
Type this on terminal

`sudo apt-get install libpng-dev`

then it works

**Comment by waelio** [comment]
> Fresh Install

**MacBook Pro - After `npm update`**
I had to update due to a lot of  **vulnerabilities**
-------------------------------------------
```
ERROR in ./app/containers/HomePage/Loadable.js 10:11
Module parse failed: Unexpected token (10:11)
You may need an appropriate loader to handle this file type.
| export default Loadable({
|   loader: function loader() {
>     return import('./index');
|   },
|   loading: LoadingIndicator
 @ ./app/containers/App/App.js 13:0-52 36:70-78
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js

```

**Comment by flexdinesh** [comment]
I updated the packages yesterday and fixed a few issues. This shouldn't happen now with the latest code.
