### ISSUE TITLE
Npm start doesnt work

### ISSUE THREAD

**Issue by shadowae** [flexdinesh/react-redux-boilerplate#2]
# After running npm start i get this error. Tried a few steps to troubleshoot but didnt work, any idea why its happening?

webpack built 7d664c5b6b1056908397 in 4699ms
✖ ｢wdm｣: 
ERROR in ./app/components/Header/images/banner.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/SatishK/IdeaProjects/movie-site2/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/SatishK/IdeaProjects/movie-site2/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./app/components/Header/Header.js 12:0-41 34:44-50
 @ ./app/components/Header/index.js
 @ ./app/containers/App/App.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
ℹ ｢wdm｣: Failed to compile.

**Comment by LifeIsPizza** [comment]
Had a similar error for a libpng library:
`libpng12.so.0: cannot open shared object file: No such file or directory`

I resolved this by reinstalling with npm after editing the package.json file

`"image-webpack-loader": "3.6.0",`
to
`"image-webpack-loader": "4.2.0",`

And then it ran smoothly.
Hope this helps

**Comment by flexdinesh** [comment]
@shadowae @LifeIsPizza I have updated the dependencies with this commit - 2bd8904142b49ef28ea57701503edc8deb28851d

`image-webpack-loader` is known to have inconsistencies with other package versions in the past and I fixed it by updating the version as @LifeIsPizza mentioned. Now that I have updated all the dependencies to the latest stable version, hopefully this should have been fixed. Let me know if you still face this issue.

**Comment by jandetlefsen** [comment]
Getting the same error with the current project state. After git pull, npm install and npm start i ended up with image-webpack-loader@4.3.1 and the described error.

**Comment by jandetlefsen** [comment]
Found the reason. Missing dependency. `sudo apt-get install libpng16-dev` did the trick

**Comment by flexdinesh** [comment]
This image webpack loader has system dependencies and they differ from one OS to another. It's been such a bummer since the beginning and we gotta figure out a platform independent way to get this to work. 

Thanks @jandetlefsen , I'm gonna close this issue out for now.
