### ISSUE TITLE
Can this boiler plate be used for making API's?

### ISSUE THREAD

**Issue by sidzan** [flexdinesh/react-redux-boilerplate#23]
I tried putting simple get request, which seems to work, but the server is not automatically restarted upon any code change. 

Can anyone recommend me if it is good to use this also as an api and also solution to restart server upon change (used nodemon, but iseems to restart multiple times for 1 change which is weird).

Any help is much appreciated !

Thank you

**Comment by flexdinesh** [comment]
I am using this as an API for one of my projects. Using `nodemon` works good for me. Make sure you ignore the `app` dir for nodemon as webpack middleware will take care of hot reloading the front-end. The idea is to use nodemon to only observe changes in `server` dir.

Here's my start script, if it helps, ignore the irrelevant parts.
`"start:local:watch": "cross-env NODE_ENV=development nodemon --ignore /app/ run-s start:local"`
