### ISSUE TITLE
css loader issues

### ISSUE THREAD

**Issue by R1714** [flexdinesh/react-redux-boilerplate#32]
Hi,

I'm try to dynamic add css. But it's take js. 
![issues](https://user-images.githubusercontent.com/20294985/52657237-379bea00-2f1e-11e9-9907-9e8e7f3f861f.PNG)

**Comment by flexdinesh** [comment]
@R1714 I'm not sure if I understand the issue correctly. But if you're trying to work with `css-modules`, you should name your files in the pattern `*.module.css`.

**Comment by brunoserralheiro** [comment]
Hello, 
Thanks for sharing the code. However, I had a problem, apparently  with sass. I use Linux Ubuntu 18.04. Even tried running npm i with sudo, but no luck. Here is the log:

32513 verbose node v8.10.0
32514 verbose npm  v6.9.0
32515 error code ELIFECYCLE
32516 error errno 1
32517 error node-sass@4.11.0 postinstall: `node scripts/build.js`
32517 error Exit status 1
32518 error Failed at the node-sass@4.11.0 postinstall script.
