### ISSUE TITLE
Need to do hard refresh on new updates.

### ISSUE THREAD

**Issue by RobertStuff** [flexdinesh/react-redux-boilerplate#39]
Hi good day.. I would like to ask if you have a solution to not do hard refresh when I update. Right now I need to do ctrl + f5 to see the changes...

**Comment by schmanat** [comment]
Really? I have tested it. If I change something (for example) in the component ```app/components/Header/Header.js```for example it update the browser instantly.

**Comment by RobertStuff** [comment]
In production?

**Comment by schmanat** [comment]
I have tested it only in develpment. Its necesarry to refresh autom. in production?

**Comment by RobertStuff** [comment]
Yup when you do update production you need to do ctrl + shift + f5 for the the frontend update to show.

**Comment by flexdinesh** [comment]
This is more like a deployment issue. Make sure you don't cache the `index.html` file. As new builds are hashed, you'll almost never run into cache issues unless you cache your `index.html` file.

**Comment by RobertStuff** [comment]
Yup thanks...
