### ISSUE TITLE
Consider adding flow

### ISSUE THREAD

**Issue by balinskia** [flexdinesh/react-redux-boilerplate#9]
What do you think about adding flow - static type checker?

**Comment by flexdinesh** [comment]
@balinskia Flow sounds interesting. But we should keep this boilerplate unopiniated, meaning, users should be able to opt the things they'd like to use. Is there a way where we could add flow as example use cases rather than integrating it to the whole codebase?

**Comment by flexdinesh** [comment]
Closing this issue as the thread has been dead for over 2 months now.
